<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Resources\Api\V1\PenaltyResource;
use App\Http\Responses\ApiResponse;
use App\Services\Penalty\PenaltyService;
use Dedoc\Scramble\Attributes\Group;
use Dedoc\Scramble\Attributes\QueryParameter;
use Dedoc\Scramble\Attributes\Response;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * View penalties charged to overdue repayments.
 *
 * A penalty is a financial charge generated automatically once a
 * repayment schedule installment's grace period has expired, resolved
 * from the applicable PenaltyRule at the time it was charged (see the
 * Loan Configuration group for the rules themselves). Penalties are
 * system-generated by the `penalties:accrue` scheduled command — there
 * is no create/update/delete endpoint here, this module is read-only.
 *
 * A penalty is always a separate financial record: it never modifies
 * the loan's principal or the repayment schedule's total_amount.
 *
 * All endpoints return the application's standard envelope:
 * `{"success": bool, "message": string, "data"?: object|null, "errors"?: object}`.
 * All endpoints require `Authorization: Bearer {access_token}` plus the
 * `penalties.view` permission.
 */
#[Group('Penalties')]
class PenaltyController extends Controller
{
    private const PENALTY_SCHEMA = 'array{id: int, loan_id: int, repayment_schedule_id: int, penalty_rule_id: int|null, amount: string, period_start_date: string, applied_date: string, status: string, reason: string|null, created_at: string, updated_at: string}';

    private const UNAUTHENTICATED_SCHEMA = 'array{success: false, message: string}';

    private const FORBIDDEN_SCHEMA = 'array{success: false, message: string}';

    private const NOT_FOUND_SCHEMA = 'array{success: false, message: string}';

    public function __construct(
        private readonly PenaltyService $penaltyService,
    ) {
        //
    }

    /**
     * List penalties
     *
     * Returns a paginated, filterable list of penalties charged across
     * all loans.
     */
    #[QueryParameter('page', description: 'Page number.', type: 'integer', default: 1)]
    #[QueryParameter('per_page', description: 'Results per page (max 100).', type: 'integer', default: 15)]
    #[QueryParameter('loan_id', description: 'Filter by loan.', type: 'integer', example: 15)]
    #[QueryParameter('repayment_schedule_id', description: 'Filter by repayment schedule installment.', type: 'integer', example: 4)]
    #[QueryParameter('status', description: 'Filter by penalty status.', type: 'string', example: 'applied')]
    #[QueryParameter('applied_date_from', description: 'Only penalties applied on or after this date.', type: 'string', example: '2026-09-01')]
    #[QueryParameter('applied_date_to', description: 'Only penalties applied on or before this date.', type: 'string', example: '2026-12-31')]
    #[Response(200, description: 'Penalties retrieved.', type: 'array{success: true, message: string, data: array{penalties: '.self::PENALTY_SCHEMA.'[], pagination: array{current_page: int, per_page: int, total: int, last_page: int}}}')]
    #[Response(401, description: 'Missing, invalid, or expired access token.', type: self::UNAUTHENTICATED_SCHEMA, examples: [[
        'success' => false,
        'message' => 'Unauthenticated',
    ]])]
    #[Response(403, description: 'Missing the penalties.view permission.', type: self::FORBIDDEN_SCHEMA, examples: [[
        'success' => false,
        'message' => 'You do not have permission to perform this action.',
    ]])]
    public function index(Request $request): JsonResponse
    {
        $request->validate([
            'loan_id' => ['nullable', 'integer', 'exists:loans,id'],
            'repayment_schedule_id' => ['nullable', 'integer', 'exists:repayment_schedules,id'],
            'status' => ['nullable', 'string'],
            'applied_date_from' => ['nullable', 'date'],
            'applied_date_to' => ['nullable', 'date'],
        ]);

        $paginator = $this->penaltyService->list($request->only([
            'loan_id', 'repayment_schedule_id', 'status', 'applied_date_from', 'applied_date_to', 'per_page', 'page',
        ]));

        return ApiResponse::success([
            'penalties' => PenaltyResource::collection($paginator)->resolve(),
            'pagination' => [
                'current_page' => $paginator->currentPage(),
                'per_page' => $paginator->perPage(),
                'total' => $paginator->total(),
                'last_page' => $paginator->lastPage(),
            ],
        ], 'Penalties retrieved successfully');
    }

    /**
     * Show a penalty
     *
     * Returns a single penalty.
     */
    #[Response(200, description: 'Penalty retrieved.', type: 'array{success: true, message: string, data: '.self::PENALTY_SCHEMA.'}')]
    #[Response(401, description: 'Missing, invalid, or expired access token.', type: self::UNAUTHENTICATED_SCHEMA, examples: [[
        'success' => false,
        'message' => 'Unauthenticated',
    ]])]
    #[Response(403, description: 'Missing the penalties.view permission.', type: self::FORBIDDEN_SCHEMA, examples: [[
        'success' => false,
        'message' => 'You do not have permission to perform this action.',
    ]])]
    #[Response(404, description: 'Penalty does not exist.', type: self::NOT_FOUND_SCHEMA, examples: [[
        'success' => false,
        'message' => 'Penalty not found.',
    ]])]
    public function show(int $penalty): JsonResponse
    {
        $model = $this->penaltyService->find($penalty);

        return ApiResponse::success(new PenaltyResource($model), 'Penalty retrieved successfully');
    }
}
